name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test with wasm-pack
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Cache Cargo dependencies
      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build with wasm-pack
        run: wasm-pack build --release --target web # https://rustwasm.github.io/docs/wasm-pack/

      #- name: Run wasm-pack test
      #  run: wasm-pack test --headless --chrome

      - name: Run Playwright tests in Docker
        uses: addnab/docker-run-action@v3
        with:
          image: mcr.microsoft.com/playwright:v1.48.1-noble
          options: --shm-size=1gb 
          run: |
            npm install
            npm test